celo-org/celo-oracle

src/aggregator_functions.ts, src/data_aggregator.ts, src/exchange_adapters/base.ts, src/utils.ts
Small changes needed further down by implicit pairs. No behaviour changes expected.
Changes are covered by current unit/integration tests.
- #11 
No exported interface was changed.
=> Some initial changes to help with implicit pairs.

src/data_aggregator.ts
Log a PriceSource's name instead of the whole object.
Unit/integration tests passed.
- #11 
Backwards compatible. Logging output will change.
=> Improve error logging.

README-metrics.md
=> Add oracle_price_source to README-metrics.md.

src/data_aggregator.ts, src/exchange_adapters/novadax.ts, src/utils.ts, test/exchange_adapters/novadax.ts
Adds a new exchange adapter for NovaDAX.
Tested on Baklava with cross-exchange implicit pairs.
Changes are backwards compatible.
=> Add NovaDAX adapter

src/exchange_adapters/base.ts, src/utils.ts
Add BUSD pairs for implicit CELOBRL.
Tested against a local node.
Fully backwards compatible.
=> Add BUSD pairs support.

src/metric_collector.ts
Made the metrics less granular.
No
=> Reduced buckets for metrics

package.json, src/utils.ts
Add a missing ticker for USDBRL
Bump version
📿 
N/A
fully.
=> Add USDBRL to configured tickers

src/data_aggregator.ts, src/exchange_adapters/whitebit.ts, src/utils.ts, test/exchange_adapters/whitebit.test.ts
This change will add an adapter for the Whitebit exchange.
N/A
- Unit tests added to verify the functionality works as intended
- Closes [#163](https://github.com/mento-protocol/mento-general/issues/163)
N/A
=> feat: add whitebit exchange adapter

src/exchange_adapters/whitebit.ts
Add missing certificate in whitebit
n/a
n/a
- Fixes [#177](https://github.com/mento-protocol/mento-general/issues/177)
n/a
=> chore: add missing certificate in whitebit

README.md
This updates the recommended config commit in the readme to the latest commit in the monorepo, which includes the USDC/EUR and USDC/BRL configurations.
=> chore: update recommended config commit

package.json, src/exchange_adapters/novadax.ts
update novadax certificate and bump version
n/a
n/a
n/a
n/a
=> chore: update novadax certificate and bump version

package.json, src/exchange_adapters/novadax.ts
Update Novadax cert fingerprint.
N/A
N/A
- On call low oracle alerts
YES
=> chore: update novadax cert and bump version

src/utils.ts
This PR adds EUROCUSD as a new currency pair.
none
Tested locally
_Brief explanation of why these changes are/are not backwards compatible._
=> New Currency Pair: EUROCUSD

.github/workflows/docker_push_oidc.yaml
Upgrading the workflow version to 1.11.2
=> adding workflow version 1.11.2

.github/workflows/docker_push_oidc.yaml
Upgrading to version v1.11.4 of the reusable workflow
=> upgrading to version v1.11.4

package.json
Bump the version to 1.0.7 to draft a new release.
=> chore: bump to 1.0.7

package.json, src/reporters/base.ts, test/reporters/base.test.ts
Gas price estimation causes a floating point number to be passed to Web3.js for gasPrice and that results in an error:
> {"message":"Error: [number-to-bn] while converting number \"8000160226.5\" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: \"8000160226.5\"","name":"Error","stack":"Error: Error: [number-to-bn] while converting number \"8000160226.5\" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: \"8000160226.5\"\n    at toBN (/celo-oracle/node_modules/web3-utils/lib/utils.js:60:15)\n    at Object.numberToHex …
=> fix: Math.ceil the gasPrice

Dockerfile
Pin 2nd docker image version as well.
_Describe any minor or "drive-by" changes here._
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
_Brief explanation of why these changes are/are not backwards compatible._
=> fix: change version in release image as well

package.json
- Update the package version
- None
- N/A
- Fixes https://github.com/mento-protocol/mento-general/issues/334
- N/A
=> chore: update package.json version to 1.0.9

package.json
bumped version in order to create new release and fix Euroc oracles
=> chore: bump version to 1.0.10

README.md
Update deployment hash after deploying binance certificate fix & bitget usdcusd misconfiguration
=> chore: update deployment config hash

package.json
Update package version to trigger a new release.
n/a
n/a
n/a
n/a
=> release: 1.0.13

package.json, src/exchange_adapters/bitso.ts, src/exchange_adapters/bittrex.ts, src/exchange_adapters/coinbase.ts, src/exchange_adapters/mercado.ts, src/exchange_adapters/okcoin.ts
Update certificates for okcoin, coinbase, bitso and mercato
N/A
Ran locally and verified data pulling works
=> fix: update okcoin, coinbase, bitso and mercato certs fingerprints

src/utils.ts
Should have been added as part of https://github.com/celo-org/celo-oracle/pull/245
Ran it locally
=> fix: add USDKES pair constants

package.json
- bump package version for new docker image
=> chore: bump package version to 2.0.2

package.json, src/exchange_adapters/currencyapi.ts
pr updates currencyapi certificate
bump version
ran oracles locally
=> fix: update currencyAPI certificate

src/exchange_adapters/coinbase.ts
Update the coinbase certificate fingerprint.
N/A
Ran locally
On-call ping
N/A
=> chore: update coinbase cert

package.json
Bump package.json version to trigger a new release
N/A
N/A
N/A
N/A
=> release: 2.0.4-beta

src/exchange_adapters/bitso.ts, src/exchange_adapters/kraken.ts
update certs for bitso and kraken 
ran oracles locally observed prices being fetched
=> chore: update certs for bitso and kraken

package.json
=> chore: bump version to 2.0.7

package.json, src/exchange_adapters/okx.ts
- Update the fingerprint of the okx cert
- Ran locally with configuration to confirm requests are successfull
=> chore: update okx cert

package.json, src/exchange_adapters/bitget.ts
- Update bitget cert
- Ran client locally
=> chore: update bitget cert fingerprint

src/exchange_adapters/binance_us.ts
- Update Binance US cert
- Ran client locally
=> chore: update binance us cert

package.json, src/exchange_adapters/bitso.ts
update bitso cert fingerprint
N/A
ran oracles locally and confirmed bitso fetching works
N/A
N/A
=> chore: update bitso cert fingerprint

src/exchange_adapters/xignite.ts
Update xignite cert
N/A
Ran oracles locally using xignite & ensured cert error was no longer present
N/A
N/A
=> chore: update xignite cert
