src/exchange_adapters/base.ts, src/exchange_adapters/binance.ts, src/exchange_adapters/bittrex.ts, src/exchange_adapters/coinbase.ts, src/exchange_adapters/okcoin.ts, test/data_aggregator_testdata_utils.ts, test/exchange_adapters/binance.test.ts, test/exchange_adapters/bittrex.test.ts, test/exchange_adapters/coinbase.test.ts, test/exchange_adapters/okcoin.test.ts
Changes the ExchangeAdapter interface by adding a `quoteVolume` field to the `Ticker` type returned by `fetchTicker()`. This field is populated with the quote currency volume (quote notional) on each adapter, except for Coinbase, as it's not provided by its API. Coinbase's adapter calculates quoteVolume from baseVolume and lastPrice.
Unit/integration tests modified to support the new field.
- Needed for #11.
Backwards compatible -- new field added to a type, all usages of the type updated.
=> Add a quoteVolume field to the Ticker type.

src/envvar_utils.ts
Check that all OrientedExchangePairConfig properties have the right type
after an object is loaded from a YAML string.
Currently an YAML loaded OrientedExchangePairConfig object might have some of its fields `undefined`. This PR ensures it doesn't happen by asserting the properties types, hence interrupting the execution if the price sources are misconfigured.
Tested on a local testnet.
- #11 
No interface changes.
=> Improve PRICE_SOURCES env var config validation.

.circleci/config.yml
As letting it pick the number of workers from the CPU count might not
work as expected on a CI environment (see
https://jestjs.io/docs/cli#--maxworkersnumstring).
=> Set jest --maxWorkers to 2.

.circleci/config.yml
Currently the `yarn install` step of the CI build does not use a cache. This PR introduces the usage of CircleCI's caching to store yarn's cache and to re-use it in between runs.
Builds triggered on CircleCI and they successfully passed.
=> Small CI Tweaks

.circleci/config.yml
The CircleCI build currently pushes docker images to the `celotestnet` container registry, and this PR points it to the `celoprod` one.
Tested the push on this branch by removing the `main` filter.
=> Change ACR push to celoprod.

src/exchange_adapters/base.ts, src/utils.ts, test/utils.test.ts
Adds support for CELOBRL rates reporting, including support for implicit pairs via BTCBRL and USDTBRL pairs.
Tested locally by reporting to the `StableTokenEUR` contract.
- Fixes #87 
As currency pairs were added, and none removed, the oracle remains fully backwards compatible.
=> Add CELOBRL support.

build.sh
Both rc1 and baklava are using celoprod/oracle now.
=> Update build.sh registries.

src/exchange_adapters/coinbase.ts, test/exchange_adapters/coinbase.test.ts
Coinbase Exchange has `limit_onlyy=true` flag checked on Coinbase, that means it can't be used for the oracles. After running some risk assessment with Pedro we decided that it was good to remove it as long as other checks are still checked. 
-
Updated
-
-
=> Update Coinbase liveness check

src/exchange_adapters/base.ts
Previously, the code would raise an exception that would crash the
executable. Now it's handled as a failed checkServerIdentity, and
price sources with failing fetches can be ignored.
From https://nodejs.org/api/tls.html#tlsconnectoptions-callback:
"checkServerIdentity(servername, cert) A callback function to be used (instead of the builtin tls.checkServerIdentity() function) when checking the server's host name (or the provided servername when explicitly set) against the certificate. This should return an Error if verification fails. The method should return undefined if the servername and cert are verified."
Tested locally.
=> Handle certificate validation failures.

src/reporters/base.ts, src/reporters/block_based_reporter.ts, test/reporters/base.test.ts
Instead of letting the client die with an exception when it's not in the list of approved oracles, the behaviour has been changed so that it logs an error message and keeps receiving block headers. The client will attempt to update the approved list every k blocks, where k is the current number of approved oracles.
=> Fix issues preventing the client from running with non-approved addresses.

src/data_aggregator.ts, src/exchange_adapters/mercado.ts, src/utils.ts, test/exchange_adapters/mercado.test.ts
added the mercadoBitcoin adapter 
Please take look at the parseTicker() function. The response is a bit different from other APIs therefore I had to use some other fields to build the Ticker object.  I left a comment explaining which and why I used those fields. 
N/A
- tested each of the functions in the adapter
- ran oracle locally
- Fixes https://github.com/mento-protocol/mento-general/issues/124
=> feat: add mercado adapter

src/utils.ts
We got an error while trying to deploy the new `USDCUSD` oracle config to alfajores and after investigating realized that it's because `USDCUSDT` and `USDTUSDC` were not defined as pairs in the client code.
Ran it locally with the latest config in https://github.com/celo-org/celo-monorepo/blob/master/packages/helm-charts/oracle/USDCUSD.yaml#L22-L27 and removing WhiteBit (this adapter has not been added yet, but lets do that in a different issue)
=> feat: add missing USDC and USDT currency pairs

README.md, build_and_publish.sh, package.json
This updates the version in the package.json to `1.0.0` to make it the first official oracle client release 🎉 From now on we will follow a more semantic versioning release process adding github releases and changelog notes.
* Updated the `build_and_publish.sh` script to use the `-w` grep parameter to not treat the version as a regex. Otherwise it would find a match even though the version didn't really existed and failed to push the image. Also made some other small changes for better readability.
* Added a `deployment` section in the readme to link to the latest recommended config that oracle providers can refer to.
- Fixes https://github.com/mento-protocol/mento-general/issues/157
=> Oracle official v1.0.0 release

src/default_config.ts
This reduces the default `gasPriceMultiplier` value from `5` to `2` as we increased it a long time ago during high network usage but we don't really have a reason for it being that high right now, so the clients are unnecessarily overpaying when sending reports.
Ran it locally and printed the configuration to check it was updated
-  This PR together with https://github.com/celo-org/celo-monorepo/pull/10182/ fixes https://github.com/mento-protocol/mento-general/issues/165
- Yes
=> fix: reduce gasPriceMultiplier

README.md, package.json
This bumps the version to 1.0.1 and updates the recommended config to fix the issue with CELOBRL not working that was recently fixed in #154 
Ran all the configs locally to make sure the client works
- Fixes https://github.com/mento-protocol/mento-general/issues/171
=> feat: bump to 1.0.1 and update recommended config

src/data_aggregator.ts, src/exchange_adapters/bitget.ts, src/exchange_adapters/gemini.ts, src/utils.ts, test/exchange_adapters/bitget.test.ts
This PR adds a Bitget exchange adapter
No
- Tested locally with BRL config (https://github.com/celo-org/celo-monorepo/pull/10194/files)
- added a Bitget test file, all tests pass
- Fixes [#164](https://github.com/mento-protocol/mento-general/issues/164) [#181](https://github.com/mento-protocol/mento-general/issues/181)
Fully
=> feat: bitget adapter

__mocks__/@celo/contractkit/index.ts, src/default_config.ts, src/metric_collector.ts, src/reporters/base.ts, src/reporters/block_based_reporter.ts, test/reporters/base.test.ts
Exposes a new metric checking the celo balance of oracle addresses 
n/a
Unit tests
- Fixes [#168](https://github.com/mento-protocol/mento-general/issues/168)
n/a
=> feat: add oracle balance metric

src/data_aggregator.ts, src/exchange_adapters/base.ts, src/exchange_adapters/bitmart.ts, src/utils.ts, test/exchange_adapters/bitmart.test.ts
This Pr adds a new exchange Adapter for Bitmart that we need for EUROCEUR reports.
The ticket mentions some additional adapters for FX rates since it seems like there are better data providers that provide more information than just the price. I would suggest we separate the ticket until we decide on which providers to use @sissnad
- N/A
- unit tests for the new adapter
- ran oracle locally to verify prices are being reported 
-> add  `[{ exchange: 'BITMART', symbol: 'EUROCUSDC', toInvert: false }],` to devPriceSourcesConfig.txt
- Fixes [239](https://github.com/mento-protocol/mento-general/issues/239)
=> feat: add Bitmart adapter

Dockerfile, dockerfiles/continuous-integration/Dockerfile
updating the node version + debian 
n/a
pushed a new [docker image](https://console.cloud.google.com/artifacts/docker/celo-testnet-production/us-west1/celo-oracle/celo-oracle/sha256:531ea25700df3c25e918af39aee354a9b67e3b80da268cb39029da1f76d36ae4) in the registry 
- Fixes https://github.com/mento-protocol/mento-general/issues/261
n/a
=> chore: update docker image to node:18

src/exchange_adapters/base.ts, src/exchange_adapters/binance.ts, src/exchange_adapters/bitget.ts, src/exchange_adapters/bitmart.ts, src/exchange_adapters/bitso.ts, src/exchange_adapters/bitstamp.ts, src/exchange_adapters/bittrex.ts, src/exchange_adapters/coinbase.ts, src/exchange_adapters/gemini.ts, src/exchange_adapters/kraken.ts, src/exchange_adapters/kucoin.ts, src/exchange_adapters/mercado.ts, src/exchange_adapters/novadax.ts, src/exchange_adapters/okcoin.ts, src/exchange_adapters/okx.ts, src/exchange_adapters/whitebit.ts, test/exchange_adapters/base.test.ts, test/exchange_adapters/bitget.test.ts, test/exchange_adapters/bitmart.test.ts, test/exchange_adapters/bitstamp.test.ts, test/exchange_adapters/bittrex.test.ts, test/exchange_adapters/coinbase.test.ts, test/exchange_adapters/gemini.test.ts, test/exchange_adapters/kucoin.test.ts, test/exchange_adapters/mercado.test.ts, test/exchange_adapters/okcoin.test.ts, test/exchange_adapters/okx.test.ts, test/exchange_price_source.test.ts
This removes all of the unused code related to trades in the codebase. I recently noticed it again in @philbow61 PR to add the [bitmart adapter](https://github.com/celo-org/celo-oracle/pull/177/files#diff-95a3025b2559ff66f41c653df3c49e0f47a2523c0e1cec17c8985bff2de3032fR25-R31) and decided to take some time to finally get rid of it.
The background on this is that at some point we thought we might want to use both trade and ticket data but we only ended up using the later.
Order changes on the imports were done by the linter
Ran the client locally for two different currency pairs
- Fixes https://github.com/celo-org/celo-oracle/issues/178
=> chore: Remove unused 'trades' related code

README.md
It should point to the EUROC/EUR config that was just merged 
https://github.com/celo-org/celo-monorepo/commit/0d433bc6b3bb0845868660281320d0a4fbba3dee
=> chore: update latest recommended config

src/data_aggregator.ts, src/exchange_adapters/currencyapi.ts, src/utils.ts, test/exchange_adapters/currencyapi.test.ts
This adds a second FX adapter (CurrencyAPI) which will be used for EURXOF rates. The logic for `isOrderbookLive` will be done in a different PR once we have the conditions defined.
N/A
- Wrote unit tests for the parsing of the ticker
- Ran it locally to ensure it works
- Fixes https://github.com/mento-protocol/mento-general/issues/309
=> feat: add currencyapi adapter

src/exchange_adapters/alphavantage.ts, src/exchange_adapters/currencyapi.ts, src/exchange_adapters/kucoin.ts, test/exchange_adapters/currencyapi.test.ts
We will be using `currencyapi.net` instead of the .com version as it has higher rate limits. 
- Update the certificate for alphavantage and kucoin that seems to have been recently updated
Unit tests + ran both adapters locally
=> fix: changes on currencyapi adapter and update expired certs

src/exchange_adapters/alphavantage.ts, src/exchange_adapters/base.ts, src/exchange_adapters/currencyapi.ts, src/metric_collector.ts, test/exchange_adapters/base.test.ts
This adds an orderbook check on the fx adapters that essentially disables them from reporting while the markets are closed on the weekends. The clients will stop reporting on Fridays 22 UTC and re-enable on Sundays 22 UTC.
-
- Unit tests for the function that establishes the closing hours, and try it locally
- Fixes https://github.com/mento-protocol/mento-general/issues/310
=> feat: add market closing hours check on fx adapters

src/data_aggregator.ts, src/exchange_adapters/xignite.ts, src/utils.ts, test/exchange_adapters/xignite.test.ts
This adds a third FX adapter (Xignite) which will be used for EURXOF rates. Similar to other FX adapters, it has the market open hours check inside `isOrderbookLive`.
N/A
- Wrote unit tests for the parsing of the ticker + timestamps
- Ran it locally to ensure it works
- Fixes https://github.com/mento-protocol/mento-general/issues/321
=> feat: add xignite fx adapter

src/exchange_adapters/alphavantage.ts, src/exchange_adapters/base.ts, src/exchange_adapters/binance.ts, src/exchange_adapters/binance_us.ts, src/exchange_adapters/bitget.ts, src/exchange_adapters/bitmart.ts, src/exchange_adapters/bitso.ts, src/exchange_adapters/bitstamp.ts, src/exchange_adapters/bittrex.ts, src/exchange_adapters/coinbase.ts, src/exchange_adapters/currencyapi.ts, src/exchange_adapters/gemini.ts, src/exchange_adapters/kraken.ts, src/exchange_adapters/kucoin.ts, src/exchange_adapters/mercado.ts, src/exchange_adapters/novadax.ts, src/exchange_adapters/okcoin.ts, src/exchange_adapters/okx.ts, src/exchange_adapters/whitebit.ts, src/exchange_adapters/xignite.ts
This essentially reverts the change made in https://github.com/celo-org/celo-oracle/pull/186, as we realized that the leaf certificates are updated too often in some of the adapters which then causes them to stop working.
While testing the adapters I realized that Binance Intl is no longer working since the /exchangeInfo endpoint returns a response that matches our hardcoded max response size (4MB), so I increased that value to 8MB instead.
Ran all the currently deployed charts locally and verified that none of them throw certificate related errors.
- Fixes https://github.com/mento-protocol/mento-general/issues/325
=> chore: update all adapters to not use leaf certificate

Dockerfile
The Docker image started from `node:18` which is an ephemeral tag that gets update to the most recent `18.*.*` version.
Recently `18.18.2` was pushed but a dependency is having trouble because it can't find pre-built binaries for that version and building them in the Docker build is failing.
Solution: pin the node version at `18.18.0`
N/A
_An explanation of how the changes were tested or an explanation as to why they don't need to be._
_Brief explanation of why these changes are/are not backwards compatible._
=> fix: pin Docker image to node:18.18.0

src/exchange_adapters/xignite.ts
This PR updates the Xignite certificate fingerprint. The previous fingerprint was outdated leading to an error in the client that stopped repors from the Xignite adapter. This update will replace the old fingerprint with the current one from the Xignite server, resolving the connection issue and restoring functionality.
- None
- Verified updated fingerprint matches the current cert from https://globalcurrencies.xignite.com
- Fixes https://github.com/mento-protocol/mento-general/issues/334
- N/A
=> fix: update XigniteAdapter certFingerprint256

src/exchange_adapters/bitmart.ts, src/utils.ts, test/exchange_adapters/bitmart.test.ts
This PR adds a new price source `EUROCUSDT`. 
- It renews the Bitmart fingerprint (but will also expire soon...)
- It adds a symbol map as Bitmart uses `EURC` instead of `EUROC`
Has been tested locally.
=> feat: add price source EUROCUSDT

package.json, src/exchange_adapters/binance.ts
Updated the binance certificate
None
Ran the client locally to ensure prices are being retrieved and reported
- Fixes [#338](https://github.com/mento-protocol/mento-general/issues/338)
N/A
=> fix: update binance certificate

src/exchange_adapters/bitget.ts
Update BitGet certificate fingerprint.
New certificate fingerprint is from the 2nd in the chain. Found via:
```
$ scripts/get_cert_fingerprint.sh api.bitget.com 2
SHA256 Fingerprint=46:49:4E:30:37:90:59:DF:18:BE:52:12:43:05:E6:06:FC:59:07:0E:5B:21:07:6C:E1:13:95:4B:60:51:7C:DA
```
Can be also verified in browser at the link: https://api.bitget.com/api/spot/v1/market/ticker
N/A
Ran configuration locally.
_Brief explanation of why these changes are/are not backwards compatible._
=> fix: update bitget certificate

src/exchange_adapters/base.ts, src/utils.ts
This adds the necessary hardcoded constants and pairs for running KES/USD and CELO/KES oracles.
N/A
Ran both oracle pairs locally
- Related to https://github.com/mento-protocol/mento-general/issues/402
=> feat add constants and pairs for KES oracles

package.json, src/reporters/block_based_reporter.ts
This fixes the issue where the client WS connections no longer reconnect after an interruption due to the web3 library upgrade that was done in https://github.com/celo-org/celo-oracle/commit/28ecb4b2c8f78a9bda9ceb7ce0ad4d38d5d522c9. The fix is done by passing an options parameter that includes a reconnect configuration whenever we instantiate a new `WebsocketProvider`. It also adds a new `reconnect` listener so that the client can log whenever it's attempting to reconnect.
There are also a few other places in the code where a "manual reconnection" is attempted by re-instantiating `WebsocketProvider` ([1](https://github.com/celo-org/celo-oracle/blob/459947a5b697473f93f1389f37410dcd93a9ac74/src/reporters/block_based_reporter.ts#L331), …
=> fix: broken ws reconnection after web3 upgrade

src/exchange_adapters/coinbase.ts, test/exchange_adapters/base.test.ts, test/exchange_adapters/coinbase.test.ts
Coinbase recently renamed EUROC to EURC in tickers etc. 
One exchange adapter base test was failing because the expected error message changed. 
Ran orcles locally with coinbase EUROC in the config.
=> fix: EUROC to EURC renaming on Coinbase

src/exchange_adapters/binance.ts, src/exchange_adapters/mercado.ts, src/exchange_adapters/novadax.ts
This PR updates certificates for mercado, binance, and novadax as well as the base endpoint for Binance. 
The updated base endpoint is recommended to be used when accessing public market data 
Ran each of the updated adapters locally in dev mode.
=> fix: update certificates for binance, mercado and novadax

package.json, src/exchange_adapters/alphavantage.ts, src/exchange_adapters/bitget.ts
Update the alphavantage certificate fingerprint and bumped the version to 2.0.6-beta
N/A
Ran it locally
=> chore: update alphavantage cert

package.json, src/exchange_adapters/binance.ts, src/exchange_adapters/okx.ts
Update Binance + OKX certs
bump package version 
ran locally with & without changes & confirmed new fingerprint fixes the error
=> chore: update binance + okx certs + bump version

package.json, pnpm-lock.yaml, src/exchange_adapters/bitso.ts, src/exchange_adapters/bittrex.ts, src/exchange_adapters/okcoin.ts, src/exchange_adapters/whitebit.ts
This PR updates the fingerprints for some of the oracles feeds
bump package version
ran locally with & without changes & confirmed new fingerprint fixes the error
=> Chore: update bitso, bittrex, okcoin & whitebit  certs + bump version
